apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myfirstapplicationcluster-3fef"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myfirstapplicationcluster-3fef"
  template:
    metadata:
      labels:
        app: "myfirstapplicationcluster-3fef"
    spec:
      containers:
        - name: "myfirstapplicationcluster-3fef"
          image: "myfirstapplicationcontainer.azurecr.io/myfirstapplicationcluster"
          ports:
          - containerPort: 8080